dim_theta: 19      # 8 + 4 + 4 + 1 + 1 + 1
dim_u: 500         # 5 * S * N => if S=2, N=50 => 5*2*50=500
S: 2            # Number of importance Samples
N: 50                     # Number of subjects
T: 6                      # Observations per subject
#lambda_val: 10     # Precision (1/variance) of the random effects
dim_per_subject: 4       # Dimension of each random effect (b_i)
n_steps: 86 # delta t (stepsize =  len_sample/n_steps)
len_sample: 30  # Length of each sample trajectory
num_samples: 200  # Number of sample trajectories to generate
test_fraction: 0.1  # Fraction of data to reserve for testing
should_load: false  # Whether to load existing data
load_dir: ""  # Directory to load data from
load_file_name: ""  # Filename to load data from
save_dir: "./pm_HMC"  # Directory to save data to
dist_name: "GLMM"  # Name of the target distribution
seed: 0