dim_theta: 19      # dimension of theta (parameters of interest)
dim_u: 500         # (1+dim_per_subject) * S * N => if S=2, N=50 => 5*2*50=500. 1 dimension for uniform mixture assignment
S: 2            # Number of importance Samples
N: 50                     # Number of subjects
T: 6                      # Observations per subject
dim_per_subject: 4       # Dimension of each random effect (b_i)
n_steps: 1000 # delta t (stepsize =  len_sample/n_steps)
len_sample: 30  # Length of each sample trajectory
num_samples: 200  # Number of sample trajectories to generate
test_fraction: 0.1  # Fraction of data to reserve for testing
should_load: false  # Whether to load existing data
load_dir: ""  # Directory to load data from
load_file_name: ""  # Filename to load data from
save_dir: "./pm_HMC"  # Directory to save data to
dist_name: "GLMM"  # Name of the target distribution
seed: 0