input_dim: 2  # Total number of variables (positions + momenta) # Must be 2 for 1D_Gauss_mix and 4 for 2D_Gauss_mix
N_lf: 20  # "cool-down" steps if integration errors are high
hnn_threshold: 10 # Threshold before manual integration substitutes L-HNN
lf_threshold: 1000 # # Threshold before subtree is abandoned for NUTS
burn: 1000 # Burn in samples for NUTS
test_fraction: 0.1
len_sample: 20
num_samples: 8000
dist_name: "1D_Gauss_mix"
save_dir: "."
load_dir: "."
latent_dim: 64
should_load: true
total_steps: 8000
hidden_dim: 100
learn_rate: 0.0005
batch_size: 1000
nonlinearity: "sine"
step_size: 0.05
print_every: 200
field_type: "solenoidal"
seed: 0